### PR TITLE
possible approach for lazy data domains

### LINKED ISSUE #236: Derive data properties (min-max, categories, ...) automatically
* Release number or git hash: v4.0.0-alpha.12
 * Web browser version and OS: 

### Observed behavior
Without using the builder to derive columns, there is no way to tell LineUp (i.e. via a Column Description flag) to automatically compute min/max, categories, ...

### Expected behavior
As columns are often dynamically added, and LineUp computes statistics such as histograms on the fly, it may be possible to derive those properties automatically (if not set explicitly).

### PR DESCRIPTION
**Pull request by sgratzl**
closes #236 

**prerequisites**:

- [x] branch is up-to-date with the branch to be merged with, i.e. develop
- [x] build is successful
- [x] code is cleaned up and formatted

## Summary

possible approach for the derive min/max automatically. This is an early version just for the NumberColumn to get early feedback (@alexsb, @thinkh , @puehringer ), cause I don't know all the practical corner cases.

### CODE REVIEW

**Review by thinkh — COMMENTED** [review]
Looks good to me and could work for our use cases.

@puehringer Will take a look at this PR next week.

File: src/model/NumberColumn.ts [hunk 1]
```diff
@@ -139,6 +142,41 @@ export default class NumberColumn extends ValueColumn<number> implements INumber
...
+
+    const domain = this.mapping.domain.slice();
+    if (this.deriveMapping[0]) {
+      domain[0] = minMax.min;
+    }
+    if (this.deriveMapping[this.deriveMapping.length - 1]) {
+      domain[domain.length - 1] = minMax.max;
+    }
+    this.mapping.domain = domain;
+    (this.original as IMappingFunction).domain = domain;
```
Comment (puehringer) [inline src/model/NumberColumn.ts:177]: @sgratzl I tested the feature and it works as expected, even though I don't exactly know why 😆 One thing that confuses me is why the column is being rerendered (i.e. marked as dirty) even though we are setting the domain _inline_ here. 
Is it because we are calling this function as part of the data update mechanism which then marks the column dirty? Then what would happen if we call the `onDataUpdate` with arbitrary data from "outside"? That would update the mapping _inline_ but would it also mark is as dirty (i.e. update the histogram bounds, ...)?

Comment (sgratzl) [reply src/model/NumberColumn.ts:177]: the data provider is triggering a full resort and thus a rerender.

File: src/model/BoxPlotColumn.ts [hunk 2]
```diff
@@ -99,6 +100,7 @@ export default class BoxPlotColumn extends ValueColumn<IBoxPlotData> implements
     super(id, desc);
     this.mapping = restoreMapping(desc, factory);
     this.original = this.mapping.clone();
+    this.deriveMapping = this.mapping.domain.map((d) => Number.isNaN(d));
```
Comment (puehringer) [inline src/model/BoxPlotColumn.ts:103]: Why exactly are we relying on `NaN` instead of `null` or `undefined`?
Without having tested it, one particular problem I see with this is when dumping the column to JSON (which leads to `NaN -> null`) and restoring it would lead to incorrect behavior, as `Number.isNaN(null) === false`.

Comment (sgratzl) [reply src/model/BoxPlotColumn.ts:103]: good point. I guess addition of null would be a good choice but requires to change the type definition to `[number|null, number|null]`

**Review by puehringer — APPROVED** [review]
Works fine in my tests, glad to see such an important feature in the next release! 🎉
