### PR TITLE
sanitize column labels, ...

### LINKED ISSUE #455: Lineup column name is prone to js injections
When I name a column `document.body.innerHTML = '';` the code gets executed

**To Reproduce**

1. Name a column `document.body.innerHTML = '';`

The column has the name, but nothing happens

image

### PR DESCRIPTION
**Pull request by sgratzl**
closes #455 

**prerequisites**:

- [x] branch is up-to-date with the branch to be merged with, i.e. develop
- [x] build is successful
- [x] code is cleaned up and formatted

## Summary

changes a bunch of renderings to avoid rendering user input as HTML

### CODE REVIEW

File: src/ui/domElementCache.ts [hunk 1]
```diff
@@ -21,3 +21,19 @@ export default function domElementCache(doc: Document): (html: string) => HTMLEl
     return node;
   };
 }
+
+export function createSanitizer(doc: Document): (v: string) => string {
+  //prepare variables
```
Comment (thinkh) [inline src/ui/domElementCache.ts:26]:
```suggestion
  // prepare variables
```

File: src/ui/dialogs/StringFilterDialog.ts [hunk 2]
```diff
@@ -60,10 +60,11 @@ export default class StringFilterDialog extends ADialog {
   }
 
   protected build(node: HTMLElement) {
+    const s = this.ctx.sanitize;
     const bak = this.column.getFilter() || { filter: '', filterMissing: false };
     node.insertAdjacentHTML(
       'beforeend',
-      `<input type="text" placeholder="Filter ${this.column.desc.label}..." autofocus
+      `<input type="text" placeholder="Filter ${s(this.column.desc.label)}..." autofocus
```
Comment (thinkh) [inline src/ui/dialogs/StringFilterDialog.ts:67]:
```suggestion
      `<input type="text" placeholder="Filter ${s(this.column.desc.label)} …" autofocus
```

**Review by thinkh — APPROVED** [review]
Thanks for the changes and the additional demo file. It looks good to me. Just a few minor changes, if you'd like to add them.
