### PR TITLE
Fix values in array column and use correct labels

### LINKED ISSUE #209: Values in the array columns are not correct
* Release number or git hash: 2d4734dd347d8becb288f76970a120f0f7db3e9b
 * Web browser version and OS: Chrome 78

### Steps to reproduce

1. Open the [demo in LineUp v3](https://lineup.js.org/app/#soccer)
2. Open the [demo in LineUp v4](https://lineup.js.org/app_develop/#soccer)
3. Compare the first value in the first row of column `Goals` in both versions 
4. Compare with the values in the underlying [data table](https://github.com/lineupjs/lineup_app/blob/develop/src/data/soccer/soccer.csv)

### Observed behavior
* In LineUp v3, the first value in the first row of the column `Goals` equals `3.00` which is the expected and correct value.
image

* In LineUp v4, the first value in the first row of the column `Goals` equals `0.0492` which is not correct.
image

### Expected behavior
 * LineUp version `3.2.2` equals version `4.0.0-alpha.12`

### PR DESCRIPTION
**Pull request by dvvanessastoiber**
closes #209 

### Summary
1. add property `labels` and assign `years` in order to receive the correct labels
2. use raw numbers instead of mapped ones in order to receive the correct values in the columns
3. in _BoxplotCellRenderer.ts_: Split `renderDOMBoxPlot()` into `renderItemDOMBoxPlot()` and `renderSummaryDOMBoxPlot()` for easier maintainance and due to the need for a `scaleLinear` for boxplots in summary

#### Items 1 and 2
Instead of years, `Column x` is used as label. Furthermore, the values are not correct.
image

#### Item 3
_boxplot.html_ example:
image

Boxplot in summary onhover: Values are incorrect (always `min = 0.00` and `may = 1.00`)
image

Boxplot within column onhover: The correct values are displayed
image

#### Items 1 and 2
Years are used as labels and the correct values are displayed.
image

#### Item 3
Summary boxplots are rendered correctly and the correct values are displayed
image

### CODE REVIEW

File: src/renderer/UpSetCellRenderer.ts [hunk 1]
```diff
@@ -22,10 +22,10 @@ export default class UpSetCellRenderer implements ICellRendererFactory {
   }
 
   private static createDOMContext(col: ISetColumn) {
-    const categories = col.categories;
+    const labels = col.labels;
     let templateRows = '';
-    for (const cat of categories) {
-      templateRows += `<div class="${cssClass('upset-dot')}" title="${cat.label}"></div>`;
+    for (const lab of labels) {
```
Comment (thinkh) [inline src/renderer/UpSetCellRenderer.ts]:
```suggestion
    for (const label of labels) {
```

I buy the two letters and would name it `label`. 😉

File: src/provider/DirectRenderTasks.ts [hunk 2]
```diff
@@ -115,11 +115,13 @@ export class DirectRenderTasks extends ARenderTasks implements IRenderTaskExectu
   }
 
   groupBoxPlotStats(col: Column & INumberColumn, group: IOrderedGroup, raw?: boolean) {
+    raw = true;
```
Comment (thinkh) [inline src/provider/DirectRenderTasks.ts]: I would rather avoid setting the flag here as it would make the parameter useless. Were you able to see the references where this function was called? Otherwise we could assign a default value to the paramter instead.

**Comment by sgratzl** [comment]
what happens atm. when one inverts the data mapping?

**Comment by thinkh** [comment]
The calculated and visualized boxplot values by LineUp are matching with the expected values in the _boxplot.html_ example. I checked the values using this page: https://goodcalculators.com/box-plot-maker/

grafik

**Comment by sgratzl** [comment]
again what if you have a numerical column, ranging from 10 to 1000 where most values are within 900 and 1000 and apply a mapping such that 10 -> 1 and 1000 -> 0. Does the boxplots in the group column or summary matches the bars?

**Comment by thinkh** [comment]
I added columns with inverted mapping to the boxplot example. The summary and grouped boxplot look like this:

grafik

Here are some catches:

* The summary boxplot of the regular columns look the same as for the inverted columns (which is wrong in my opinion)
* Onnly the min and max value below the boxplot are switched for the inverted columns (which is correct)
* The group boxplot, however, is mirrored for the inverted column (which is correct in my opinion)

grafik


@sgratzl Is there something else wrong/missing?

**Comment by dvvanessastoiber** [comment]
New fix:
* revert to single `renderDOMBoxPlot()`
* change `createSummary` according to `createGroup`: 
	* Use `mappedSummary` for calculation and `rawSummary` for correct labels
	* Use `tasksAll` and set the `raw` flag to `false` first, then to `true`

Now the boxplots for the inverted columns are correct as well
image

As well as the labels:
image

File: src/renderer/BoxplotCellRenderer.ts [hunk 3]
```diff
@@ -179,21 +180,20 @@ function renderDOMBoxPlot(col: INumberColumn, n: HTMLElement, data: IBoxPlotData
     outliers.unshift(p);
     whiskers.insertAdjacentElement('afterend', p);
   }
-
-  data.outlier.forEach((v, i) => {
+  data.outlier!.forEach((v, i) => {
```
Comment (thinkh) [inline src/renderer/BoxplotCellRenderer.ts]: Do we still need the `!` with the most recent changes? Otherwise we could remove it again. Also further down.

Comment (dvvanessastoiber) [reply src/renderer/BoxplotCellRenderer.ts]: I have reverted the unnecessary changes and everything still works fine. Thanks!

**Comment by thinkh** [comment]
Thanks @dvvanessastoiber!

@sgratzl From our side it is working correctly now. Could you please have a look again?

File: src/renderer/HeatmapCellRenderer.ts [hunk 4]
```diff
@@ -56,7 +57,7 @@ export default class HeatmapCellRenderer implements ICellRendererFactory {
         if (renderMissingDOM(n, col, d)) {
           return;
         }
-        n.onmousemove = mover(n, col.getLabels(d));
+        n.onmousemove = mover(n, col.getRawNumbers(d).map(formatter));
```
Comment (sgratzl) [inline src/renderer/HeatmapCellRenderer.ts]: why is this change necessary?

File: src/renderer/HistogramCellRenderer.ts [hunk 5]
```diff
@@ -24,7 +24,7 @@ export default class HistogramCellRenderer implements ICellRendererFactory {
           return;
         }
         const b = normalizedStatsBuilder(guessedBins);
-        for (const n of col.getNumbers(row)) {
+        for (const n of col.getRawNumbers(row)) {
```
Comment (sgratzl) [inline src/renderer/HistogramCellRenderer.ts]: mixing `normalizedStatsBuilder` with raw numbers - the normalized stats builder uses certain assumptions thus should only be used for normalized data.

File: src/renderer/UpSetCellRenderer.ts [hunk 6]
```diff
@@ -22,10 +22,10 @@ export default class UpSetCellRenderer implements ICellRendererFactory {
   }
 
   private static createDOMContext(col: ISetColumn) {
-    const categories = col.categories;
+    const labels = col.labels;
     let templateRows = '';
-    for (const cat of categories) {
-      templateRows += `<div class="${cssClass('upset-dot')}" title="${cat.label}"></div>`;
+    for (const label of labels) {
```
Comment (sgratzl) [inline src/renderer/UpSetCellRenderer.ts]: why is this change necessary?

File: src/renderer/HeatmapCellRenderer.ts (hunk 4 above)
Comment (thinkh) [reply src/renderer/HeatmapCellRenderer.ts]: Not necessary, as `getLabels()` does the formatting internally.

https://github.com/lineupjs/lineupjs/blob/9dcbf5fb4cd66579304f612812dc9e001ae553ac/src/model/NumbersColumn.ts#L176-L178

File: src/renderer/UpSetCellRenderer.ts (hunk 6 above)
Comment (thinkh) [reply src/renderer/UpSetCellRenderer.ts]: Because the tooltip for the UpSet renderer was `undefined`.

**Before this change**

grafik

grafik


**After this change**

grafik

grafik

Comment (thinkh) [reply src/renderer/UpSetCellRenderer.ts]: Because the tooltip for the UpSet renderer was `undefined`.

**Before this change**

grafik

grafik


**After this change**

grafik

grafik

File: src/renderer/HistogramCellRenderer.ts (hunk 5 above)
Comment (thinkh) [reply src/renderer/HistogramCellRenderer.ts]: The idea was to show the raw numbers for the bin size, as the bin size is normalized, which is confusing with the scales below (see also #212).

grafik

After testing it again, it does not work, so I reverted this line.

**Comment by thinkh** [comment]
@sgratzl Thanks for your review. I addressed your comments. Please have a look again.

File: src/renderer/UpSetCellRenderer.ts (hunk 6 above)
Comment (sgratzl) [reply src/renderer/UpSetCellRenderer.ts]: > UpSet renderer

the upset renderer is mainly used for categorical or set columns. Categorical Arrays is a corner case. So it seems like that the category generation might be wrong but imo the Upset renderer should be just based on categories.

Comment (thinkh) [reply src/renderer/UpSetCellRenderer.ts]: Ok. I reverted this part.

**Comment by thinkh** [comment]
@sgratzl Please have one last look. If there are no open points, please merge this PR. Thanks.
