### PR TITLE
Taggle overview mode

### LINKED ISSUE #551: Taggle should respect sidePanel option
Taggle.ts does not respect the sidePanel option. Specifically, you can see LineUp.ts does respect the option here: [https://github.com/lineupjs/lineupjs/blob/main/src/ui/LineUp.ts#L38](https://github.com/lineupjs/lineupjs/blob/main/src/ui/LineUp.ts#L38), whereas Taggle.ts does not: [https://github.com/lineupjs/lineupjs/blob/main/src/ui/taggle/Taggle.ts#L45](https://github.com/lineupjs/lineupjs/blob/main/src/ui/taggle/Taggle.ts#L45)

**To Reproduce**

1. const builder = lineupBuilder(...);
2. builder.sidePanel(false, true);
3. builder.buildTaggle(...);

**Expected behavior**

With this code, I would expect the sidePanel to be entirely disabled, instead, it still shows.

**Context**

- Version: v4.5.0
- Browser: Chrome

**Additional context**

It is possible that this is an intentional design decision because right now the toggle for switching to overview mode is only exposed in the sidePanel. In that case, I would suggest respecting the sidePanel option, and also exposing the overview mode explicitly. In other words, making [updateLodRules](https://github.com/lineupjs/lineupjs/blob/main/src/ui/taggle/Taggle.ts#L90) a public function, and perhaps changing the name to something like setOverviewMode.

This came up for my use case where am using LineUp as a component in a larger visualization system. For this, I would like to include the overview option, but do not want to include the sidePanel to try and simplify the UI where possible :)

### PR DESCRIPTION
**Pull request by sgratzl**
closes #551

**prerequisites**:

- [x] branch is up-to-date with the branch to be merged with, i.e. develop
- [x] build is successful
- [x] code is cleaned up and formatted

## Summary

refactor overview mode toggle to be set via `setOverviewMode`. In addition, allow to disable the side panel within Taggle

### CODE REVIEW

File: src/ui/taggle/Taggle.ts [hunk 1]
```diff
@@ -87,6 +87,22 @@ export default class Taggle extends ALineUp {
     );
   }
 
+  isOverviewMode() {
+    return this.renderer?.getRule() == this.spaceFillingRule;
```
Comment (puehringer) [inline src/ui/taggle/Taggle.ts:91]: I suppose the Github Action with the warning `Expected '===' and instead saw '=='` is correct and should be fixed?

**Review by puehringer — CHANGES_REQUESTED** [review]

File: src/ui/taggle/Taggle.ts (hunk 1 above)
Comment (sgratzl) [reply src/ui/taggle/Taggle.ts]: fixed

**Review by puehringer — APPROVED** [review]
Looks good to me! 🎉
