### PR TITLE
Fix canvas horizontal shift issue

### LINKED ISSUE #224: Rows shift to the left side (under wrong column headers) in the Overview Mode
* Release number or git hash: LineUp v4
 * Web browser version and OS: Google Chrome Version 79.0.3945.117 (Offizieller Build) (64-Bit)

### Steps to reproduce

1. Insert enough columns or increase the displayed column(s) width to enable a horizontal scroll bar in the display
2. Switch to the overview mode.
3. The rows will shift to the left, thereby, pointing to the wrong column headers.
4. Upon dragging the horizontal scrollbar, the content snaps to the original position for some columns.

### Observed behavior
 
Overview Issue

### PR DESCRIPTION
**Pull request by sgratzl**
closes #224

**prerequisites**: 
 * [x] branch is up-to-date with the branch to be merged with, i.e. develop
 * [x] build is successful
 * [x] code is cleaned up and formatted 
 * [ ] tested with Firefox 52, Firefox 57+, Chrome 64+, MS Edge 16+

### Summary

before:

before

after:

scrollbug

the issue was the the canvas rendering logic didn't consider the optimized horizontal rendering logic. Thus, didn't update when a column to the left was not rendered anymore (shift to left) or the width changes (missing content on the right)

### CODE REVIEW

File: src/ui/EngineRanking.ts [hunk 1]
```diff
@@ -615,6 +619,7 @@ export default class EngineRanking extends ACellTableSection<RenderColumn> imple
   }
 
   protected updateRow(node: HTMLElement, rowIndex: number, hoverLod?: 'high' | 'low'): void {
+    console.log('update row', rowIndex);
```
Comment (thinkh) [inline src/ui/EngineRanking.ts]: Do you want to keep this log?

Comment (sgratzl) [inline src/ui/EngineRanking.ts]:
```suggestion
```
